version: "3"
services:
  eureka:
    build: ./eureka-server
    image: yunterry/eureka
    ports:
      - 8761:8761

  provider:
    build: ./service-provider
    image: yunterry/service-provider
    ports:
      - 2017
    links:
      - eureka

  consumer:
    build: ./feign-consumer
    image: yunterry/feign-consumer
    ports:
      - 3000
    links:
      - eureka

  gateway:
    build: ./zuul-gateway
    image: yunterry/zuul-gateway
    ports:
      - 4000
    links:
      - eureka

  hystrix:
    build: ./hystrix-turbine
    image: yunterry/hystrix-turbine
    ports:
      - 5000
    links:
      - eureka
